'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace My


	<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")> _
	Friend NotInheritable Partial Class Settings
		Inherits System.Configuration.ApplicationSettingsBase

		Private Shared defaultInstance As Settings = (CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()), Settings))

		Public Shared ReadOnly Property [Default]() As Settings
			Get
				Return defaultInstance
			End Get
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("`~!@#$%^&*()-_=+[]\{}|;':"",./<>?")> _
		Public Property Symbols() As String
			Get
				Return (DirectCast(Me("Symbols"), String))
			End Get
			Set(ByVal value As String)
				Me("Symbols") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("QWERTY")> _
		Public Property KeyboardLayout() As String
			Get
				Return (DirectCast(Me("KeyboardLayout"), String))
			End Get
			Set(ByVal value As String)
				Me("KeyboardLayout") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("False|False|False")> _
		Public Property Rules() As String
			Get
				Return (DirectCast(Me("Rules"), String))
			End Get
			Set(ByVal value As String)
				Me("Rules") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("6")> _
		Public Property NumberOfChars() As Decimal
			Get
				Return (DirectCast(Me("NumberOfChars"), Decimal))
			End Get
			Set(ByVal value As Decimal)
				Me("NumberOfChars") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("False|True|True|True")> _
		Public Property CharsToUse() As String
			Get
				Return (DirectCast(Me("CharsToUse"), String))
			End Get
			Set(ByVal value As String)
				Me("CharsToUse") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("1")> _
		Public Property MinDigits() As Decimal
			Get
				Return (DirectCast(Me("MinDigits"), Decimal))
			End Get
			Set(ByVal value As Decimal)
				Me("MinDigits") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("1")> _
		Public Property MinLower() As Decimal
			Get
				Return (DirectCast(Me("MinLower"), Decimal))
			End Get
			Set(ByVal value As Decimal)
				Me("MinLower") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("1")> _
		Public Property MinUpper() As Decimal
			Get
				Return (DirectCast(Me("MinUpper"), Decimal))
			End Get
			Set(ByVal value As Decimal)
				Me("MinUpper") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("1")> _
		Public Property MinSymbols() As Decimal
			Get
				Return (DirectCast(Me("MinSymbols"), Decimal))
			End Get
			Set(ByVal value As Decimal)
				Me("MinSymbols") = value
			End Set
		End Property
	End Class
End Namespace
